// cse datas

//1
let cse=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//3
{title:"GAMING-ROOM",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//4
{title:"HORROR-HOUSE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//5
{title:"THIMARPPU-DJ",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//6
{title:"AMAZE-COSMOS",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//7
{title:"SPIES-IN-DISGUISE",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//8
{title:"DEBUG",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//9
{title:"BLIND-CODING",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//10
{title:"CRACK-THE-CODE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//11
{title:"FAST-FINGERS",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//12
{title:"CRYSTAL-CANVAS",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//13
{title:"SPIN-THE-WEB",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//14
{title:"OS-MODEL-EXHIBITION",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//15
{title:"EDUTHO-PIDICHO",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//16
{title:"DARTS-SHOOTOUT",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//17
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//18
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//19
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//20
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//21
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//22
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//23
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//24
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//25
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//26
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//27
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//28
{title:"WORLD-OF-HARRY-POTTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},
]

let mech=[{title:"Mecholution",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Machinery-EXPO",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Mech-Corner",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Lathe-Master",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Design-Competition",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Workshop",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Project-EXPO",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Penalty-shootout",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Workshop",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Project-EXPO",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Penalty-shootout",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"}]

let civil=[{title:"Planetarium",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"},
{title:"Flight-Simulator",para:"Internet services and applications have become an inextricable part of daily lifeenabling communication and the management of personal information from anywhere",room:"201",fee1:"40",fee2:"60",coordinator1:"Afkar",coordinator1no:"1234567890",coordinator2:"mrudula",coordinator2no:"0987654321"}]




module.exports={mech,civil,cse}
