// cse datas

//1
let cse=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR) Experience, Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"GAMING-ROOM",
para:"Gaming consoles, FIFA and other games",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each",
rule2:"",
room:"506",fee1:"50rs per head",
coordinator1:" Gopika M",
coordinator1no:" 6235451723",
coordinator2:" Amritha Devadasan",
coordinator2no:"8075942401"},


//3
{title:"THIMARPPU-DJ",
para:"Entertainment with DJ",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"",
room:"Room No. 219",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:" Arjun S",
coordinator1no:"9061225608",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9994071758"},

//4
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball.",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//5
{title:"HORROR-HOUSE",
para:"Horror & Entertainment",
grules:"General Rules:",
rule1:"Mobiles Phones will not be allowed to the room.",
rule2:"Once entered then they can leave at the end point.",
rule3:"Entry fee will not be refunded.",
rule4:"Don't touch the Ghost.",
rule5:"Do not damage any equipments",
room:"Room No. 202",fee1:"Rs. 40/- per head",
fee2:"Rs. 60/- per team (2)",coordinator1:" Sajid P M",
coordinator1no:"7306619945",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//4
{title:"SPIES-IN-DISGUISE",
para:"Tasks based on a Crime Investigation.",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each.",
rule2:"Do not damage any equipments.",
rule3:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 207",fee1:"Rs. 30/- per person",
fee2:"",coordinator1:" Swetha A",
coordinator1no:"7306606253",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//5
{title:"AMAZE-COSMOS",
para:"Puzzle game, Solve the tasks given",
grules:"General Rules:",
rule1:"Mobile Phones will not be allowed into the room.",
rule2:"Once entered then they can leave at the end point",
rule3:"Entry fee will not be refunded.",
rule4:"Do not damage any equipments.",
room:"Room No. 209",fee1:"Rs. 40/- per head, 60/- per team (2)",
fee2:"",coordinator1:" Anusree CN",
coordinator1no:"8590953496",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//7
{title:"DEBUG",
para:"Coding with Black Screen, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:" Anirudh",
coordinator1no:"9778105494",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//8
{title:"BLIND-CODING",
para:"Coding with Black Screen, Errors need to be found, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Nithya",
coordinator1no:"9037349107",
coordinator2:"Akhila E",
coordinator2no:"9847788306"},


//10
{title:"FAST-FINGERS",
para:"Typing Competition, Participants need to type the content in time, Gift worth of 500.",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per team of 3",
fee2:"",coordinator1:"Midhun",
coordinator1no:"8075543158",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//11
{title:"CRYSTAL-CANVAS",
para:"Digital Painting, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 40 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Nimmi",
coordinator1no:"9037008834",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//12
{title:"SPIN-THE-WEB",
para:"Web development competition, Gift worth 500",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Sumesh",
coordinator1no:"9645633049",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//13
{title:"OS-MODEL-EXHIBITION",
para:"Different models of OS Exhibition",
grules:"General Rules:",
rule1:"should not damage any equipment, if done fine will be charge.",
room:"Room No. 216",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:" Rohith",
coordinator1no:"7034380685",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},


//14
{title:"WORLD-OF-HARRY-POTTER",
para:"Experience the magical life of Harry Potter",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"",
room:"Room No. 218",fee1:"Rs. 30/- per team (2)",
fee2:"",coordinator1:" Malavika",
coordinator1no:"9400216229",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},

//15
{title:"EDUTHO-PIDICHO",
para:"Ring Throw,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each person will get 3 chances",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 20/- per person",
fee2:"",coordinator1:" Fahad",
coordinator1no:"9946749918",
coordinator2:"",
coordinator2no:""},

//16
{title:"DARTS-SHOOTOUT",
para:"Throw the Darts at the point,Gift will be provided",
grules:"General Rules:",
rule1:"3 throws per person",
rule2:"",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:" Madhan Raj",
coordinator1no:"7994669252",
coordinator2:" Ramya TV",
coordinator2no:"9400916341 "},

//17
{title:"PERFECT-RUBIKS-CUBE",
para:"Rubik’s Cube will be provided,Participant need to solve the cube,Gift will be provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:" ",
room:"Indoor stadium",
fee1:"Rs. 10/- per person",
fee2:"",coordinator1:":  Fahad",
coordinator1no:"9946749918",
coordinator2:" Ramya TV",
coordinator2no:"9400916341 "},

//18
{title:"HARDWARE-ASSEMBLY",
para:"Assembling Hardware Components",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"ADS Lab",fee1:"FREE",
fee2:"",coordinator1:" Emmanuel Eldho",
coordinator1no:"7012112740",
coordinator2:" Akhila E",
coordinator2no:"9847788306 "},

//19
{title:"MINUTE-TO-WIN-IT",
para:"Fun Games and Activities in 1 Minute,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:" Niranjana S",
coordinator1no:"8590509055",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},

//20
{title:"FUN-TUSSLE",
para:"Troll making based on Technical Topic",
grules:"General Rules:",
rule1:"should not be copied from any platform.",
rule2:"",
rule3:"",
rule4:"",
room:"ONLINE",fee1:"10/- Per head",
fee2:"",coordinator1:"Aswin A R",
coordinator1no:"9745142622",
coordinator2:"Akhila E",
coordinator2no:"9847788306 "},

//21
{title:"MAGIC-OF-FINGERS",
para:"Poster making Competition based on given topic, Participant can make poster on their devices or system provided from the college",
grules:"General Rules:",
rule1:"Poster making Competition based on given topic.",
rule2:"Participant can make poster on their devices or system provided from the college",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",
fee1:"Rs. 150/- per team of 3",
fee2:"10 per person",
coordinator1:"Akshay Krishna",
coordinator1no:"6238940904",
coordinator2:"Akhila E",
coordinator2no:"9847788306",
},

//22
{title:"PIC-POW",
para:"Spot Photography Event,Cash Prize of 500",
grules:"General Rules:",
rule1:"	One person must send only one photo",
rule2:"	Anyone submitting 2 or more photos from same participant will be disqualified.",
rule3:"	Editing other than manipulation is allowed.",
room:"Online Event",
fee1:"10/- Per head",
fee2:"",
coordinator1:" Shaheer P V",
coordinator1no:"9895730591",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//24
{title:"SUIII",
para:"Jump high as Cristiano Ronaldo’s jump height, Gift worth 500",
grules:"General Rules:",
rule1:"Two chance per person",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Garden",
fee2:"Free",
coordinator1:"Mohammed Niyaz",
coordinator1no:"8848806940",
coordinator2:" Anu TP",
coordinator2no:"9846634066"},

{title:"DEATH-MAZE",
para:"A maze is a type of puzzle games where a player moves in complex and branched passages to find a particular target or location.",
grules:"General Rules:",
rule1:"Mobile phones will not be allowed",
rule2:"Only one participant at a time",
rule3:"Entry fee will not be refunded",
rule4:"There will be a time limit to complete the maze",
room:"Room No 413",
fee2:"Rs. 10 per person",
coordinator1:"Aswin k",
coordinator1no:"9526796263",
coordinator2:"Dr. N Gunashekaran",
coordinator2no:"9894329192"},

//25
{title:"PENALTY-SHOOTOUT",
para:"",
grules:"General Rules:",
rule1:"One chance ",
rule2:"The decision of the authorities will be final and irrefutable",
room:"Ground",
fee2:"10/- Per head",
coordinator1:"Piyush Santhosh",
coordinator1no:"8086392043",
coordinator2:"Anu TPU ",
coordinator2no:"984663406"},

//26
{title:"QUIZZIE-BUZZIE",
para:"Quiz based Technical Topic,Gift worth 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
room:"Room No. 216",
fee1:"Free",
coordinator1:" Mohammed Hussain",
coordinator1no:"7025707936",
coordinator2:" Anu TP",
coordinator2no:"9846634066"},

//27
{title:"ETHICAL-HACKING-AWARENESS",
para:"Awareness about Ethical Hacking",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"506",fee1:"FREE",
coordinator1:"Gopika M",
coordinator1no:"6235451723",
coordinator2:"Amritha Devadasan",
coordinator2no:"8075942401"}
]




//aero datas

//1
let aero=[{title:"PLANETARIUM",
para:"15 minutes of realistic space experience, chance to go beyond our planet and explore what lies unseen.",
grules:"General Rules:",
rule1:"30 persons can watch at the same time ",
rule2:"Registration is required with Rs.120 per head . ",
rule3:"",
rule4:"",   
room:"CLASS ROOM 1",
fee1:"Rs. 120/- per head",
fee2:"",
coordinator1:"Surabhi",
coordinator1no:"8848870510 ",
coordinator2:"Kailash Karunakaran ",
coordinator2no:"9745143634"},


//2
{title:"FLIGHT-SIMULATOR",
para:"Flight simulator is a chance of experiencing a realistic cockpit for yourself with the virtual piloting of Cessna . A Flight Simulator with Joy Stick and an Online flight simulator will be brought.",
grules:"General Rules:",
rule1:"Simulation is done currently for free.",
rule2:"Registration is required",
rule3:"The event is open for all . ",  
rule4:"",
room:"BTech block Room No.208",
fee1:"Rs. 50/- per head",
fee2:"",
coordinator1:"Anand D ",
coordinator1no:"7558020984 ",
coordinator2:"Kailash Karunakaran",
coordinator2no:"9745143634 "},


//3
{title:"GLIDER-MODELLING",
para:"Ever tried making a plane yourself? This workshop will help in making, fabricating and flying it on your own.",
grules:"General Rules: ",
rule1:"Registration is required with Rs.150 per team . ",
rule2:"  The team can have 2 members ",
rule3:"Registration is required ",
rule4:"Limited seats are only available",   
room:"3rd floor Smart class room ",
fee1:"",
fee2:" RS. 150/- for a team of two",
coordinator1:"Gopika Gopinath ",
coordinator1no:"8606342293",
coordinator2:"Mohamed Sameer T.K ",
coordinator2no:"8547279042"},


//4
{title:"ILLUSION-HALL",
para:"An exhibition of anamorphic illusion sculpture. An illusion is a distortion of the senses, which can reveal how the mind normally organizes and interprets sensory stimulation",
grules:"General Rules: ",
rule1:"This event has registration of  ₹ 10 per head	",
rule2:"  Registration is required ",
rule3:"The event is open for all.",
rule4:"",   
room:"BTech block Room No.409",
fee1:"Rs 10/- per head",
fee2:"",
coordinator1:"Sreelakshmi N ",
coordinator1no:"9946942380 ",
coordinator2:"Amal Raj ",
coordinator2no:"9447843204"},



//5
{title:"JET-ENGINE-PROTOTYPE",
para:"Your fascination of Jet Engine will be fed through this prototype where you can feel the afterburner of a jet engine & learn how it works.",
grules:"General Rules:",
rule1:"",
rule2:"  ",
rule3:"",
rule4:" ",   
room:" Stall",
fee1:"",
coordinator1:"Jovin Joseph Saratho ",
coordinator1no:"9961548115",
coordinator2:"Rinchu P",
coordinator2no:"8593081848"},

{title:"CUBESATE",
para:"Have you ever wondered how a satellite works and what is the manufacturing procedures, then this seminar is dedicated for you. It's a live workshop of the Cubesate",
grules:"General Rules:",
rule1:"This workshop has registration of  ₹200   per head",
rule2:"Registration is required ",
rule3:"The event is open for all",
rule4:"Student ID’s must be carried",   
room:"3rd floor Seminar hall",
fee1:"Rs. 200/- per head",
coordinator1:"Abhishek P S",
coordinator1no:"9207356485",
coordinator2:"Ajith V S",
coordinator2no:"8667704870"},

//6
{title:"BRAIN-CYCLE",
para:"Test the working of the brain simultaneously.",
grules:"General Rules: ",
rule1:"The participant have to ride the bicycle through a predefined path . But there is mystery hidden in bicycle",
rule2:"  ",
rule3:"",
rule4:" ",   
room:"B.Arch Road",
fee1:"Rs 30/- per head",
fee2:"",
coordinator1:"Sreeraj.S",
coordinator1no:"9526447267",
coordinator2:"John George v",
coordinator2no:" 9791287775"},

//7
{title:"BATTLE-ROYAL",
para:"A harmless live battleroyal game, which is a replica of the mobile game PUBG, where bullets are converted to laser.",
grules:"General Rules: ",
rule1:"The duration of the game is 15 minutes ",
rule2:"A team of 3 can participate ",
rule3:"A laser toy gun is used as the weapon",
rule4:"",   
room:"BTech block room no 303",
fee1:"Rs. 10/- per head ",
fee2:"Rs. 30/- per team",
coordinator1:"Aparna.S",
coordinator1no:"7558948835",
coordinator2:"Mohamed Sameer T K",
coordinator2no:"8547279042"},


//8
{title:"LASER-MAZE",
para:"A laser orientated maze with the task to travel a path without touching the laser and bring the item from the centre of the maze",
grules:"General Rules: ",
rule1:"The duration of the game is 10 minutes ",
rule2:"A maze is constructed using the rays of laser  ",
rule3:"A participant must follow the path by without touching the laser",
rule4:" ",   
room:"BTech block room no 302",
fee1:"Rs 20/- per head",
fee2:"",
coordinator1:"Adarsh.K",
coordinator1no:"7306574413",
coordinator2:"Mohamed Sameer T K",
coordinator2no:"8547279042"},


//9
{title:"MAGNIX",
para:"Had an innovative idea and always tried to share it but never had a chance. This is your chance to come forward and present your innovative mind. Do your poster presentation on the recent trends in engineering .",
grules:"General Rules: ",
rule1:"The Competition is open to everyone.",
rule2:"Each participant is allowed to submit only one entry.",
rule3:"The Poster has to be in English.  And contain all information in one single poster.",
rule4:"The topic of the competition is “Electric propulsion and advanced fuel cell development for electric vehicle”, and participants must follow the topic.",   
room:"BTech block room no 507",
fee1:"Rs. 100/- per head ",
coordinator1:"Noora A K ",
coordinator1no:"7736769244",
coordinator2:"Amal Raj ",
coordinator2no:"9447843204"},


//10
{title:"PHOTOGRAPHY-COMPETITION",
para:"A place to exhibit your skill in photography and be judged by your efficiency and creativity.All the Photographs will be exhibited",
grules:"General Rules: ",
rule1:"Mobile phone can only be used  ",
rule2:"The topic will be provided on 8th of December 2022 and the participants should bring its coloured hardcopy in A3 paper.",
rule3:"Manipulation and watermark not allowed .",
rule4:"Photos must be in JPEG or JPG format . ",   
room:"BTech block Room No.406",
fee1:"Rs. 20/- per head ",
coordinator1:"Swathi Krishna K ",
coordinator1no:"8086680049",
coordinator2:"Sujesh G ",
coordinator2no:"9745169994"},



//11
{title:"REVERSE-CAR-PARKING",
para:"It is a type of parking where you have to reverse your car into a parking spot.",
grules:"General Rules:",
rule1:"Car driving license is mandatory",
rule2:"The car is allowed to move forward only two times",
rule3:"Disqualified if the engine goes off",
rule4:"",   
room:"GROUND",
fee1:"Rs. 30/- per head ",
fee2:"",
coordinator1:"Kasyap subramannian.P ",
coordinator1no:"8547331262",
coordinator2:"John George ",
coordinator2no:"9791287775"},



//12
{title:"DODGE-BALL",
para:" It is a team sport in which players of two teams try to throw balls and hit opponents, while avoiding being hit themselves.",
grules:"General Rules:",
rule1:"4 members in a team",
rule2:"Time duration is 20 minutes.",
rule3:"Player are not allowed to kick or step on the ball",
rule4:"Only 10 seconds ball is allowed to hold",   
room:"BTech block Room No.211",
fee1:"",
fee2:" Rs. 100/- per team",
coordinator1:"Abdul Gani. P ",
coordinator1no:"9544921476",
coordinator2:"Kailash Karunakaran",
coordinator2no:"9745143634"},



//13
{title:"SLOW-CYCLE",
para:" It is a game where the participants need to ride the cycle as slow as possible and the one who completes last with falling down or dropping leg will be the winner.",
grules:"General Rules:",
rule1:"Basic slow cycle rules.",
rule2:"Winner will be selected based on the time duration",
rule3:"Single track event based on time",
rule4:"Open for everyone.",   
room:"",
fee1:"Rs. 10/- per head ",
fee2:"",
coordinator1:"Adithyan. P ",
coordinator1no:"9747933794",
coordinator2:"Rinchu.P",
coordinator2no:"8137886456"},



//14
{title:"KICK-START",
para:"Beat the horse power with your girls power",
grules:"General Rules:",
rule1:"For all girls",
rule2:"3 attempts are only provided",
rule3:"",
rule4:"",   
room:"B.Arch road",
fee1:"Rs. 10/- per head",
fee2:"",
coordinator1:"Abhijith D Giri",
coordinator1no:"9995324820",
coordinator2:"Mohamed Sameer T K",
coordinator2no:"8547279042"}
]

//mech datas

//1
let mech=[{title:"Mecholution",
para:"The expo aims to show the transition of motorbikes from 2 stroke vehicles to the present advanced electric and hybrid vehicles. Vehicles representing each decade will be incorporated to register the evolution. The exhibition will attract the youth and will clearly emphasize the advancements happened in the domain.",
grules:"General Rules:",
rule1:"Visitors are not allowed to touch the exhibited vehicles.",
rule2:"Pictures should be taken with the permission of volunteers.",
rule3:"",
rule4:"",
room:"Parking area near transformer",fee1:"FREE",
fee2:"",coordinator1:"Mohammed Safwan C T",
coordinator1no:"6235466610",
coordinator2:"Chamind E C",
coordinator2no:"9746797978"},


//2
{title:"Lathe-Master",
para:"It is a competition where participants will be provided the required design with proper dimensions. 1. The participants should make the algorithm and CNC code for making the design ,Partcipats will be provided with material, they should reproduce the same design,The competition aims to share a real work floor experience to the participants.",
grules:"General Rules:",
rule1:"The competition will be active for the two days of NSITE 2022",
rule2:"Participants can come to the venue and participate in the event at anytime, the start time and end time will be noted to calculate the total machining time.",
rule3:"The work will be valued with respect to the machining time, dimensional correctness, quality of the work.",
rule4:"The winner of the competition will be announced at the end of second day (9th Dec 2022) after checking every entries",
room:"Mechanical Lab",fee1:" Rs.50",
fee2:"",coordinator1:" Jithin J",
coordinator1no:"7510502110",
coordinator2:"Velayudhan",
coordinator2no:"9442940493"},


{title:"Design-Enthusiast",
para:"The components list and specification of an assembly will be published in advance, the participants should design and assemble it using any designing software. The finished assembly file should be submitted at the competition venue and it should be explained as well.",
grules:"General Rules:",
rule1:"Students from any technical domain can participate.",
rule2:"The presentation should be clear explaining each step",
rule3:"The venue will be open from morning to afternoon for the participants",
rule4:"The result will be published at end of the after valuing each entry,Plagiarism must be avoided",
room:"CADD Lab",fee1:"Rs.50",
fee2:"",coordinator1:" Jishnu K",
coordinator1no:"7034912451",
coordinator2:"Nishanth S",
coordinator2no:"8089615432"},


{title:"MECH-Corner",
para:"A place or stall that depicts the present scope of mechanical engineering, domains that can be reached by mechanical engineers, latest trends of the sector, mechanism of machines. It also includes the write-ups and videos of our alumni’s who are working in different reputed organizations. They will be sharing their experiences and explaining the scope as well. There will be technical quiz section for the visitors.",
grules:"General Rules:",
rule1:"Visitors may not be permitted to use the machines or any equipment exhibited without permission.",
rule2:"Prizes to the Quiz section will be delivered at the venue itself.",
rule3:"",
rule4:"",
room:" Mechanical Lab",fee1:"FREE",
fee2:"",coordinator1:"Abhay",
coordinator1no:"8448983707",
coordinator2:"Vishnu Narayan",
coordinator2no:"8089615432"},


{title:"Machinery-Expo",
para:"The expo will show the up gradations of machineries from the conventional heavy machines to most advanced automatic, AI implemented machines. Its carried out collaborating with SIEMENS. The program will definitely show light towards the developing side of machineries to young and budding engineers.",
grules:"General Rules:",
rule1:"Visitors are not permitted to touch or use the equipment displayed.",
rule2:"Photos should be captured only with the permission of officials",
rule3:"",
rule4:"",
room:"Parking area near transformer",fee1:"FREE",
fee2:"",coordinator1:"Nidhun P N",
coordinator1no:"8139896474",
coordinator2:"Krishnaprasad",
coordinator2no:"9846819648"},

{title:"Project-Expo",
para:"The projects developed by the Mechanical Engineering Department in the previous years will be presented in an attractive manner. The program will show case the innovations made by the engineering students in previous years. The exhibition will be intriguing, thought provoking and motivating to the new students",
grules:"General Rules:",
rule1:"Visitors are not permitted to touch or use the equipment displayed.",
rule2:"Photos should be captured only with the permission of volunteers",
rule3:"",
rule4:"",
room:"Near Mechanical Lab",fee1:"FREE",
fee2:"",coordinator1:"Mohammed Fadal",
coordinator1no:"7510790263",
coordinator2:"Vishnu Narayan",
coordinator2no:"8089615432"},

{title:"Tech-Talk-Industry4.0: Industrial Robotics & Artificial Intelligence",
para:"A Technical Talk on the topic “Industry4.0: Industrial Robotics & Artificial Intelligence” by Dr. Santhakumar Mohan (Associate Professor, ME Dept, IIT Palakkad). The talk might be giving new project ideas to the students and will reflect in applications of innovative technologies.",
grules:"General Rules:",
rule1:"Participants should register through the google form published on or before 8thDecember 2022",
rule2:"The seats will be limited to 50 participants",
rule3:"E-Certificates will be provided after successful completion of the program",
rule4:"",
room:"Seminar Hall",fee1:"FREE",
fee2:"",coordinator1:" Kiran",
coordinator1no:"9188832485",
coordinator2:"Chamind E C",
coordinator2no:"9746797978"},

{title:"Bullet-Kick-Start-for-Girls",
para:"The participants will be given chance to kick start an old model bullet. It will be a challenging as well as fun experience to the students. ",
grules:"General Rules:",
rule1:"Participation restricted to females.",
rule2:"3 chances will be given to each participant",
rule3:"Entry Charge should be remitted before entering the venue",
rule4:"The chances will be on the basis of first come – first serve",
rule5:"Prize will be awarded to those participants who start the vehicle",
room:"Near Mechanical Lab",fee1:"Rs.20",
fee2:"",coordinator1:" Saurav S",
coordinator1no:"7510520728",
coordinator2:"Nishanth S",
coordinator2no:"8089615432"},

{title:"Wire-loop-Game",
para:"A wire loop game is a game which involves guiding a metal loop (a 'probe') along a serpentine length of wire without touching the loop to the wire. The loop and wire are connected to a power source in such a way that, if they touch, they form a closed electric circuit",
grules:"General Rules:",
rule1:"Single chance will be given to each participant.",
rule2:"Entry Charge should be remitted before entering the venue",
rule3:"The chances will be on the basis of first come – first serve",
rule4:"Prize will be awarded to those participants who complete the task",
rule5:"",
room:"Parking area near transformer",fee1:"Rs.20",
fee2:"",coordinator1:"Arun M",
coordinator1no:"7510520728",
coordinator2:"Vishnu Narayan",
coordinator2no:"8089615432"},

{title:"Wake-the-Kid-inside",
para:"The participant will be provided with a metal wheel and a stick to control the motion of wheel. The participant should race the wheel through the prepared track and the time taken to complete the race will be noted. Prizes will be awarded to 3 participants who completed the race in minimum time at end of each day ",
grules:"General Rules:",
rule1:"Two chances will be given to each participant",
rule2:"Entry Charge should be remitted before entering the venue",
rule3:"The chances will be on the basis of first come – first serve",
rule4:"Prize will be awarded to three participants who complete in minimum time",
rule5:"Winners list will be published at the end of each day",
room:"Parking area near transformer",fee1:" Rs.20",
fee2:"",coordinator1:"Ashik",
coordinator1no:"9061956947",
coordinator2:"Krishnaprasad",
coordinator2no:"9846819648"},

{title:"Head-Ball",
para:"A football will be hung on a specified height which will be a challenging one for each participant. The participants should try to head the ball at that height. Prize will be awarded to shoes participants who complete the task.",
grules:"General Rules:",
rule1:"Three chances will be given to each participant",
rule2:"Entry Charge should be remitted before entering the venue",
rule3:"The chances will be on the basis of first come – first serve",
rule4:"Prize will be awarded to the participants who complete the task",
rule5:"",
room:"Parking area near transformer",fee1:" Rs.20",
fee2:"",coordinator1:"Salman Ul Faris",
coordinator1no:"8136810761",
coordinator2:"Krishnaprasad",
coordinator2no:"9846819648"},

{title:" Penalty-Shootout",
para:"Participants will be given 5 chances to shoot the ball and those who finishes with 3 goals in a row will be awarded the prize",
grules:"General Rules:",
rule1:"Five chances will be given to each participant",
rule2:"Entry Charge should be remitted before entering the venue",
rule3:"The chances will be on the basis of first come – first serve",
rule4:"Prize will be awarded to the participants who complete with three goals in a row",
rule5:"",
room:"Near Mechanical Lab",fee1:": Rs.20",
fee2:"",coordinator1:"Gulzar Khan",
coordinator1no:"6238180288",
coordinator2:"Nishanth S",
coordinator2no:"8089615432"},

{title:"Volleyball-Tournament",
para:" ",
grules:"General Rules:",
rule1:"No rotation is required",
rule2:"3 sets of 15 points each",
rule3:"12 members + 1 manager can represent each team",
rule4:"Entry restricted to students who represent any educational institution",
rule5:"Registration closes on 2nd December 2022",
room:"Indoor Stadium",fee1:"Rs.1000",
fee2:"",coordinator1:"Nidhun P M",
coordinator1no:"8139896474",
coordinator2:"Chamind E C",
coordinator2no:"9746797978"}

]


//ece datas

//1
let ece=[{title:"DARK-ROOM",
para:"Entertainment, Horror, Treasure Hunt",
grules:"General Rules:",
rule1:"Entertainment, Horror, Treasure Hunt",
rule2:"",
rule3:"",
rule4:"",
room:"ROOM NO : 106",fee1:"30/-",
fee2:"",coordinator1:"HARIKRISHNAN (S5) ",
coordinator1no:"8590370441",
coordinator2:"SANISH V S",
coordinator2no:"95393 12142"},


//2
{title:"WORKSHOP",
para:"This masterclass will break down the cryptocurrency financial market and help you explore and capitalize on the opportunities available in this booming industry. A new age with a new financial system has begun, and now is the time to get in and take hold of the early investor's advantage. This course will teach you what you need to kickstart your investment journey and propel you into online investing and accumulating digital assets. You will learn to distinguish between cryptocurrency and your current fiats (legal tender that is connected to a government-issued currency) and discover why the current system has disadvantages.",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"ROOM NO :  320",fee1:"50/-",
fee2:"",coordinator1:"SUDHINA S (S5) ",
coordinator1no:"9995402888",
coordinator2:"SANISH V S",
coordinator2no:"9539312142"},

//3
{title:"CIRCUIT-DEBUGGING",
para:"The event  test the ability of participants to find errors in circuits and correct them.",
grules:"General Rules:",
rule1:"Individual participation",
rule3:"",
rule4:"",
room:"ROOM NO : 313",fee1:"30/-",
fee2:"",coordinator1:"SAVITHA S (S5) ",
coordinator1no:"8593925345",
coordinator2:"SASIKUMARAN",
coordinator2no:"95390 42534"},


//4
{title:"DIGITAL-POSTER-DESIGNING-COMPETITION",
para:"To bring out the creative expression of students.",
grules:"General Rules:",
rule1:"Theme will be givwn",
rule2:"individual participants",
rule3:"",
rule4:"",
room:"room no 510",fee1:"20/-",
fee2:"",coordinator1:"AMEENUL FATHIMA(S5)",
coordinator1no:"9544698016",
coordinator2:" SASIKUMARAN",
coordinator2no:"9539042534"},


//5
{title:"ELECTRONIC-PUZZLE",
para:"To make students familiarised with the electronic components",
grules:"General Rules:",
rule1:"Breadboard and components will be given",
rule2:"Individual participation",
rule3:"Set up and find out the output of given circuit",
rule4:"",
room:"ROOM NO : 311",fee1:"30/-",
fee2:"",coordinator1:"UMA G (S5) ",
coordinator1no:"8590408805",
coordinator2:"GEETHA M K",
coordinator2no:"99467 10883"},


//6
{title:"SOLDERING-COMPETITION",
para:"To recognize the best skills in hand soldering complex printed board assemblies",
grules:"General Rules:",
rule1:"Solder the given circuit Components will be given ",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"30/-",
fee2:"",coordinator1:"SMRITHI(S3) ",
coordinator1no:"7306827772   ",
coordinator2:"PAULOSE",
coordinator2no:"9846004307"},

//7
{title:"ARDUINO-CODING-COMPETITION",
para:"The goal of Arduino is to create an accessible way for software developers to enter the world of microcontroller programming. To encourage coding skills among students.",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"510 (CAD LAB, 4TH FLOOR)",fee1:"30/-",
fee2:"",coordinator1:"ASHA K (S5) ",
coordinator1no:"9061697028",
coordinator2:"SANISH V S",
coordinator2no:" 9539312142"},


//8
{title:"QUIZ",
para:"Students may try their best to answer the questions in less time.",
grules:"General Rules:",
rule1:"General round",
rule2:"Technical round",
rule3:"Two participants / team",
rule4:"",
room:"ROOM NO- 320",fee1:"50/-",
fee2:"",coordinator1:"ANUSREE S(3) ",
coordinator1no:"8590708320",
coordinator2:"",
coordinator2no:""},

//9
{title:"CREATIVE-PHOTOGRAPHY",
para:"Aims to recognize and reward visionary artist using photographic processes and images.",
grules:"General Rules:",
rule1:"Photo taken should be posted in the Official Instagram page.",
rule2:"Photo should be taken from the Campus with in these two Days",
rule3:"",
rule4:"",
room:"CAMPUS",fee1:"50/-",
fee2:"",coordinator1:"SEMNAS T M (S5) ",
coordinator1no:"7306461210",
coordinator2:"SUKESH",
coordinator2no:"9567418015"},


//10
{title:"VIRTUAL-DRIVING",
para:"To explore 3D environment that is meant to be interacted with by it's user",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"CAMPUS",fee1:"30/-",
fee2:"",coordinator1:"JITHIN (S3) ",
coordinator1no:"92073 28204",
coordinator2:"REMYA K P",
coordinator2no:"94959 69349"},


//11
{title:"TRACK-RACING",
para:"Form of racing where individuals race opponents in an unordered path.",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Reach the Destination without hitting the obstacles",
rule3:"",
rule4:"",
room:"321",fee1:"30/-",
fee2:"",coordinator1:"MOHD SHIBIN K P (S5) ",
coordinator1no:"9567064301",
coordinator2:"HASEENA P",
coordinator2no:"8281279616"},


//12
{title:"STACK-ATTACK",
para:"Arrange the paper glass in the form of pyramid",
grules:"General Rules:",
rule1:"Single chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"AKHILADAS (S7) ",
coordinator1no:"6238073172",
coordinator2:"SUNIL KUMAR",
coordinator2no:"9496838812"},


//13
{title:"LANDING-PAD",
para:"Catch the thrown disc by a platform and arrange one by one",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Group of Two",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"AMITH MOHAN(S7) ",
coordinator1no:"6238992663       ",
coordinator2:"SUNIL KUMAR",
coordinator2no:"9496838812"},


//14
{title:"HIT-THE-POINT",
para:"Blow off the balloons with air gun. ",
grules:"General Rules:",
rule1:"Single chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"SHADIYA  (S5)",
coordinator1no:"7902451383",
coordinator2:"REMYA K P",
coordinator2no:"9495969349"},


//15
{title:"BOWLING-ALLEY",
para:"The narrow track along which balls are roled during a game of balling ",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"ANOOP KUMAR (S7) ",
coordinator1no:"8086501763",
coordinator2:"HASEENA P",
coordinator2no:"8281279616"},


//16
{title:"NUTSTRACKER",
para:"The goal is to create a free standing tower of metal nuts",
grules:"General Rules:",
rule1:"Single chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"JASNA P Y (S7) ",
coordinator1no:"9605571112",
coordinator2:"PAULOSE",
coordinator2no:"98460 04307"},


//17
{title:"COMBINATION-PUZZLE",
para:"Rubix cube solving",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Group of Two",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"SHAHANA V S (S7) ",
coordinator1no:"8086647854",
coordinator2:"GEETHA M K",
coordinator2no:"9946710883"},


//18
{title:"PING-TAC-TOE",
para:"Out of the glasses throw the given ball in the glass which has water. ",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"SOORAJ S  (S7)",
coordinator1no:"7907335191",
coordinator2:"SASIKUMAR",
coordinator2no:"9539042534"},


//19
{title:"SUCK-UP-THE-SKITTLES",
para:"Suck up the candies with a straw as fast as possible. ",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"RANJUMON C D  (S7)",
coordinator1no:"9744963427",
coordinator2:"HASEENA P",
coordinator2no:"8281279616"},

//20
{title:"SUM-UP-TO-30",
para:"Bring the ball by blowing through an unknown path to different numbers given and must sum up to 30 within 4 chances",
grules:"General Rules:",
rule1:"Single Chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institute",fee1:"10/-",
fee2:"",coordinator1:"REMYA K P",
coordinator1no:"94959 69349",
coordinator2:"SHYHANA V S (S7)",
coordinator2no:"7560936719"},

//21
{title:"WALKER-BOTTLE",
para:"Players must flip the bottle so that it ,makes a complete 360 and lands upright.",
grules:"General Rules:",
rule1:"Single chance",
rule2:"Individual participation",
rule3:"",
rule4:"",
room:"Way to Jawaharlal Aviation Institutes",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},



{title:"DART",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"RUBENS-TUBE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"EVOLUTION-OF-ELECTRONICS",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"SATELLITE-COMMUNICATION",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"COMMUNICATION-SYSTEM",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"MINI-METRO",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"SATELLITE-BUILDING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"ARDUINO",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},


{title:"E-WASTE-MANAGEMENT",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""}
]


//civil datas

//1
let civil=[{title:"litricon",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:" Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"OOZE-LAGOON",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",
coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Piano",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"Autocad-Workshop",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"CIVIL-SPECTACLE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"FAST-TRACK",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"NOSTALGIC-SHOP",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"3s-FOOTBALL",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"WOODEN-CASTLE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",fee1:"",
fee2:"",coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""}
]


//law datas

//1
let law=[{title:"THE-SOUVENIR",
para:"Introduces the field of its kind on legal heritage and to introduce about the rights and duties as the part of the society,Spot events shall be conducted in between for the visitors Free entry for all.",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"Nehru Academy of Law Premises",fee1:"",
fee2:"",coordinator1:"NEHA MATHEW",
coordinator1no:" 6282525574",
coordinator2:"DONIYA ELSA THOMAS:",
coordinator2no:"9496439651"},

{title:"THE-QUIZ-SHOW",
para:": Quiz is being conducted to create legal awareness among the students also to have the spirit of legal knowledge among all rounds:There shall be three rounds in total,In Round- I, there shall be negative marks for each wrong answer,In each round two questions each carrying 10 marks shall be asked,Each passing question shall have 5 marks. (Maximum 1 minute),Round II There shall be no negative marking,Round III will be buzzer round,",
grules:"General Rules:",
rule1:"The quiz will cover topics related to: Constitution General Knowledge Basic History and Science",
rule2:"Each Team shall consist of two participants",
rule3:"Mass answering is not entertained,Registration amount shall not be refunded,Participants are restricted from carrying any type of electronic gadgets, books or other reference material along with them,Judges decision shall be final",
rule4:"Coordinators shall have the right to amend the rules of the event",
room:"Shastra Hall- JCET Campus",
fee1:"100 per team",
fee2:"",
coordinator1:"THEERTHA REGHUNATH",
coordinator1no:"8848778280",
coordinator2:"MEERA T",
coordinator2no:": 9645420111"},


{title:"BRAVE-HEART",
para:"Extempore is a speech competition in which the topic shall be given on the spot They shall be given specified time for preparation and the speech shall be delivered. They will be allowed to participate only in their respective registered languages (English/Malayalam).",
grules:"General Rules:",
rule1:"Participants are free to participate individually, The registration fee shall be Rs.100 per participant Rounds: There shall be only one round.",
rule2:"If necessary a knock-out round will be conducted, The participant shall be allowed to participate only in the registered language (English/Malayalam), The topic will be given at the event venue.No participant will be allowed to choose the topic again",
rule3:"Time will be strictly followed, no extra time will be given Each participant shall be given four minutes to speak on a topic and the maximum time limit to think on the topic shall be limited to two minutes. A bell will ring at the end of three minutes to indicate that one minute is left to finish his/her speech, Another bell will ring at the end of four minutes",
rule4:"No alteration of participant will be allowed on the final day All the participant must report the concerned committee members 30 minutes before the scheduled time of the competition. The decision of the panel of judges and organizing committee regarding evaluation is final and binding, Registration amount shall not be refunded",
room:"Nehru Academy of Law Premises",
fee1:"200 per participants",
fee2:"",coordinator1:"NAFEESA THASNI K",
coordinator1no:"9746152483",
coordinator2:"DIVYA S",
coordinator2no:"8594051624"},


{title:"KNIVES-OUT",
para:"A team shall consist of 4 members. The event aims at learning about the circumstances surrounding a crime scene during the collection of physical evidence and analysis of the same. It is multidisciplinary and involves a systematic search of the crime scene with observation and documentation of the scene.",
grules:"General Rules:",
rule1:"All the participants are required to carry their own writing and drawing tools and examboard (one for a team). Each team comprising four participants shall be given maximum of 8 minutes to investigate the crime scene and jot-down relevant points.Teams can make rough sketches or graphs for their convenience during this time, Participants can analyze the crime scene and physical evidence by observing. Each team shall be required to record the observation in a given sheet and submit the investigation report. The Organizing Committee will provide Reporting Sheets. Each team shall be required to hypothesize the best possible story behind the incident and conclude the guilt of the suspect/s.",
rule2:"Participants shall be directed to the crime scene once they get acquainted with the plot",
rule3:"",
rule4:"",
room:"Nehru Academy of Law ",fee1:". 600 per team",
fee2:"",coordinator1:"ADARSH G K",
coordinator1no:"7034732170",
coordinator2:"MAYA MAYURA",
coordinator2no:"8921361452"},

{title:"HAMILTON",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ROGUE-TRADER",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"UNCHARTED",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"THE-MAD-MEN",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"MARGIN-CALL",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"THE-CREATIVE-BRAIN",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PHOTOGRAPHY-CONTEST",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"STAND-UP-COMEDY",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"SPOON-AND-CUP-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"INTELLECTUAL-GAME",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"LAVA-WALK",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PENALTY-SHOOTOUT",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PS4-GAME",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"SUMO-WRESTLING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-SHOOTING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ARROW-THROW",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"RING-THROW",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PUSH-UP-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"HANGING-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ARM-WRESTLING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"CUP-AND-PLATE-TOWER-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-CATERPILLAR",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-POPPING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},
]


//mba datas

//1
let mba=[{title:"WISDOM-MAN-CORPORATE-MANAGER",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:" Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"BOOM-BANG",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"FOOTBALL-FEVER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"PARALLEL-WORLD-AR-VR",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"LETS-NACHO",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"MIND-TWISTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"DRAGON-SHOE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}
]









module.exports={mech,civil,cse,aero,ece,law,mba}
