// cse datas

//1
let cse=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR) Experience, Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Sreekala R",
coordinator2no:"8606314431"},


//27
{title:"GAMING-ROOM",
para:"Gaming consoles, FIFA and other games",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each",
rule2:"",
room:"506",fee1:"50rs per head",
coordinator1:" Gopika M",
coordinator1no:" 6235451723",
coordinator2:" Amritha Devadasan",
coordinator2no:"8075942401"},


//6
{title:"THIMARPPU-DJ",
para:"Entertainment with DJ",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"",
room:"Room No. 219",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:" Arjun S",
coordinator1no:"9061225608",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9994071758"},

//2
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball.",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:" Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//3
{title:"HORROR-HOUSE",
para:"Horror & Entertainment",
grules:"General Rules:",
rule1:"Mobiles Phones will not be allowed to the room.",
rule2:"Once entered then they can leave at the end point.",
rule3:"Entry fee will not be refunded.",
rule4:"Don't touch the Ghost.",
rule5:"Do not damage any equipments",
room:"Room No. 202",fee1:"Rs. 40/- per head",
fee2:"Rs. 60/- per team (2)",coordinator1:" Sajid P M",
coordinator1no:"7306619945",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//4
{title:"SPIES-IN-DISGUISE",
para:"Tasks based on a Crime Investigation.",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each.",
rule2:"Do not damage any equipments.",
rule3:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 207",fee1:"Rs. 30/- per person",
fee2:"",coordinator1:" Swetha A",
coordinator1no:"7306606253",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//5
{title:"AMAZE-COSMOS",
para:"Puzzle game, Solve the tasks given",
grules:"General Rules:",
rule1:"Mobile Phones will not be allowed into the room.",
rule2:"Once entered then they can leave at the end point",
rule3:"Entry fee will not be refunded.",
rule4:"Do not damage any equipments.",
room:"Room No. 209",fee1:"Rs. 40/- per head, 60/- per team (2)",
fee2:"",coordinator1:" Anusree CN",
coordinator1no:"8590953496",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},


//7
{title:"DEBUG",
para:"Coding with Black Screen, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:" Anirudh",
coordinator1no:"9778105494",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//8
{title:"BLIND-CODING",
para:"Coding with Black Screen, Errors need to be found, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Nithya",
coordinator1no:"9037349107",
coordinator2:"Akhila E",
coordinator2no:"9847788306"},


//10
{title:"FAST-FINGERS",
para:"Typing Competition, Participants need to type the content in time, Gift worth of 500.",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per team of 3",
fee2:"",coordinator1:"Midhun",
coordinator1no:"8075543158",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//11
{title:"CRYSTAL-CANVAS",
para:"Digital Painting, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 40 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Nimmi",
coordinator1no:"9037008834",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//12
{title:"SPIN-THE-WEB",
para:"Web development competition, Gift worth 500",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Sumesh",
coordinator1no:"9645633049",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//13
{title:"OS-MODEL-EXHIBITION",
para:"Different models of OS Exhibition",
grules:"General Rules:",
rule1:"should not damage any equipment, if done fine will be charge.",
room:"Room No. 216",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:" Rohith",
coordinator1no:"7034380685",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},


//14
{title:"WORLD-OF-HARRY-POTTER",
para:"Experience the magical life of Harry Potter",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"",
room:"Room No. 218",fee1:"Rs. 30/- per team (2)",
fee2:"",coordinator1:" Malavika",
coordinator1no:"9400216229",
coordinator2:" Sreekala R",
coordinator2no:"8606314431"},

//15
{title:"EDUTHO-PIDICHO",
para:"Ring Throw,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each person will get 3 chances",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 20/- per person",
fee2:"",coordinator1:" Fahad",
coordinator1no:"9946749918",
coordinator2:"",
coordinator2no:""},

//16
{title:"DARTS-SHOOTOUT",
para:"Throw the Darts at the point,Gift will be provided",
grules:"General Rules:",
rule1:"3 throws per person",
rule2:"",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:" Madhan Raj",
coordinator1no:"7994669252",
coordinator2:" Ramya TV",
coordinator2no:"9400916341 "},

//17
{title:"PERFECT-RUBIKS-CUBE",
para:"Rubik’s Cube will be provided,Participant need to solve the cube,Gift will be provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:" ",
room:"Indoor stadium",
fee1:"Rs. 10/- per person",
fee2:"",coordinator1:":  Fahad",
coordinator1no:"9946749918",
coordinator2:" Ramya TV",
coordinator2no:"9400916341 "},

//18
{title:"HARDWARE-ASSEMBLY",
para:"Assembling Hardware Components",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"ADS Lab",fee1:"FREE",
fee2:"",coordinator1:" Emmanuel Eldho",
coordinator1no:"7012112740",
coordinator2:" Akhila E",
coordinator2no:"9847788306 "},

//19
{title:"MINUTE-TO-WIN-IT",
para:"Fun Games and Activities in 1 Minute,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:" Niranjana S",
coordinator1no:"8590509055",
coordinator2:" Ramya TV",
coordinator2no:"9400916341"},

//20
{title:"FUN-TUSSLE",
para:"Troll making based on Technical Topic",
grules:"General Rules:",
rule1:"should not be copied from any platform.",
rule2:"",
rule3:"",
rule4:"",
room:"ONLINE",fee1:"10/- Per head",
fee2:"",coordinator1:" Aswin A R",
coordinator1no:"9745142622",
coordinator2:" Akhila E",
coordinator2no:"9847788306 "},

//21
{title:"MAGIC-OF-FINGERS",
para:"Poster making Competition based on given topic,	Participant can make poster on their devices or system provided from the college",
grules:"General Rules:",
rule1:"Poster making Competition based on given topic.",
rule2:"Participant can make poster on their devices or system provided from the college",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",
fee1:"Rs. 150/- per team of 3",
fee2:"10 per person",
coordinator1:" Akshay Krishna",
coordinator1no:"6238940904",
coordinator2:"Akhila E",
coordinator2no:"9847788306",
},

//22
{title:"PIC-POW",
para:"Spot Photography Event,Cash Prize of 500",
grules:"General Rules:",
rule1:"	One person must send only one photo",
rule2:"	Anyone submitting 2 or more photos from same participant will be disqualified.",
rule3:"	Editing other than manipulation is allowed.",
room:"Online Event",
fee1:"10/- Per head",
fee2:"",
coordinator1:" Shaheer P V",
coordinator1no:"9895730591",
coordinator2:" Akhila E",
coordinator2no:"9847788306"},


//24
{title:"SUIII",
para:"Jump high as Cristiano Ronaldo’s jump height, Gift worth 500",
grules:"General Rules:",
rule1:"Two chance per person",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Garden",
fee2:"Free",
coordinator1:"Mohammed Niyaz",
coordinator1no:"8848806940",
coordinator2:" Anu TP",
coordinator2no:"9846634066"},

{title:"DEATH-MAZE",
para:"A maze is a type of puzzle games where a player moves in complex and branched passages to find a particular target or location.",
grules:"General Rules:",
rule1:"Mobile phones will not be allowed",
rule2:"Only one participant at a time",
rule3:"Entry fee will not be refunded",
rule4:"There will be a time limit to complete the maze",
room:"Room No 413",
fee2:"Rs. 10 per person",
coordinator1:"Aswin k",
coordinator1no:"9526796263",
coordinator2:"Dr. N Gunashekaran",
coordinator2no:"9894329192"},

//25
{title:"PENALTY-SHOOTOUT",
para:"",
grules:"General Rules:",
rule1:"One chance ",
rule2:"The decision of the authorities will be final and irrefutable",
room:"Ground",
fee2:"10/- Per head",
coordinator1:":  Piyush Santhosh",
coordinator1no:"8086392043",
coordinator2:"  Anu TPU ",
coordinator2no:"984663406"},

//26
{title:"QUIZZIE-BUZZIE",
para:"Quiz based Technical Topic,Gift worth 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
room:"Room No. 216",
fee1:"Free",
coordinator1:" Mohammed Hussain",
coordinator1no:"7025707936",
coordinator2:" Anu TP",
coordinator2no:"9846634066"},

//27
{title:"ETHICAL-HACKING-AWARENESS",
para:"Awareness about Ethical Hacking",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"506",fee1:"FREE",
coordinator1:"Gopika M",
coordinator1no:"6235451723",
coordinator2:"Amritha Devadasan",
coordinator2no:"8075942401"}
]
