// cse datas

//1
let cse=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR) Experience, Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//27
{title:"GAMING-ROOM",
para:"Gaming consoles, FIFA and other games",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each",
rule2:"",
room:"506",fee1:"50rs per head",
coordinator1:"Ms. Gopika M",
coordinator1no:" 6235451723",
coordinator2:"Ms. Amritha Devadasan",
coordinator2no:"8075942401"},


//6
{title:"THIMARPP-DJ",
para:"Entertainment with DJ",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 216",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Arjun S",
coordinator1no:"9061225608",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9994071758"},

//2
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//3
{title:"HORROR-HOUSE",
para:"Horror & Entertainment",
grules:"General Rules:",
rule1:"Mobiles Phones will not be allowed to the room.",
rule2:"Once entered then they can leave at the end point.",
rule3:"Entry fee will not be refunded.",
rule4:"Don't touch the Ghost.",
rule5:"Do not damage any equipments",
room:"Room No. 202",fee1:"Rs. 40/- per head",
fee2:"Rs. 60/- per team (2)",coordinator1:"Mr. Sajid P M",
coordinator1no:"7306619945",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341"},


//4
{title:"SPIES-IN-DISGUISE",
para:"Tasks based on a Crime Investigation.",
grules:"General Rules:",
rule1:"Each round will be 20 minutes each.",
rule2:"Do not damage any equipments.",
rule3:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 207",fee1:"Rs. 50/- per team of 2",
fee2:"",coordinator1:"Ms. Swetha A",
coordinator1no:"7306606253",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341"},


//5
{title:"AMAZE-COSMOS",
para:"Puzzle game, Solve the tasks given",
grules:"General Rules:",
rule1:"Mobile Phones will not be allowed into the room.",
rule2:"Once entered then they can leave at the end point",
rule3:"Entry fee will not be refunded.",
rule4:"Do not damage any equipments.",
room:"Room No. 306",fee1:"Rs. 40/- per head, 60/- per team (2)",
fee2:"",coordinator1:"Ms. Anusree CN",
coordinator1no:"8590953496",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341"},


//7
{title:"DEBUG",
para:"Coding with Black Screen, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//8
{title:"BLIND-CODING",
para:"Coding with Black Screen, Errors need to be found, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//9
{title:"CRACK-THE-CODE",
para:"Writing the apt Code, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//10
{title:"FAST-FINGERS",
para:"Typing Competition, Participants need to type the content in time, Gift worth of 500.",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Systems Lab",fee1:"Rs. 20/- per team of 3",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//11
{title:"CRYSTAL-CANVAS",
para:"Digital Painting, Gift worth of 500",
grules:"General Rules:",
rule1:"Each round will be 40 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//12
{title:"SPIN-THE-WEB",
para:"Web development competition, Gift worth 500",
grules:"General Rules:",
rule1:"Each round will be 30 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"ADS Lab",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Arjun T",
coordinator1no:"9961041854",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//13
{title:"OS-MODEL-EXHIBITION",
para:"Different models of OS Exhibition",
grules:"General Rules:",
rule1:"should not damage any equipment, if done fine will be charge.",
room:"Room No. 219",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Rohith",
coordinator1no:"7034380685",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//14
{title:"WORLD-OF-HARRY-POTTER",
para:"Experience the magical life of Harry Potter",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 218",fee1:"Rs. 30/- per team (2)",
fee2:"",coordinator1:"Ms. Malavika",
coordinator1no:"9400216229",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},

//15
{title:"EDUTHO-PIDICHO",
para:"Ring Throw,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each person will get 3 chances",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 20/- per head",
fee2:"",coordinator1:"Mr. Fahad",
coordinator1no:"9946749918",
coordinator2:"",
coordinator2no:""},

//16
{title:"DARTS-SHOOTOUT",
para:"Throw the Darts at the point,Gift will be provided",
grules:"General Rules:",
rule1:"3 throws per person",
rule2:"",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:"Mr. Madhan Raj",
coordinator1no:"7994669252",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341 "},

//17
{title:"PERFECT-RUBIKS-CUBE",
para:"Rubik’s Cube will be provided,Participant need to solve the cube,Gift will be provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:" ",
room:"Room No. 218",
fee1:"Rs. 30/- per team(2)",
fee2:"",coordinator1:": Mr. Fahad",
coordinator1no:"9946749918",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341 "},

//18
{title:"HARDWARE-ASSEMBLY",
para:"Assembling Hardware Components",
grules:"General Rules:",
rule1:"• Each round will be 20 minutes each",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"ADS Lab",fee1:"FREE",
fee2:"",coordinator1:"Mr. Emmanuel Eldho",
coordinator1no:"7012112740",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306 "},

//19
{title:"MINUTE-TO-WIN-IT",
para:"Fun Games and Activities in 1 Minute,Gifts will be Provided",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable",
rule3:"",
rule4:"",
room:"Indoor Stadium",fee1:"Rs. 10/- per head",
fee2:"",coordinator1:"Ms. Niranjana S",
coordinator1no:"8590509055",
coordinator2:"Ms. Ramya TV",
coordinator2no:"9400916341"},

//20
{title:"FUN-TUSSLE",
para:"Troll making based on Technical Topic",
grules:"General Rules:",
rule1:"should not be copied from any platform.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"ONLINE",fee1:"10/- Per head",
fee2:"",coordinator1:"Mr. Aswin A R",
coordinator1no:"9745142622",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306 "},

//21
{title:"MAGIC-OF-FINGERS",
para:"Poster making Competition based on given topic,	Participant can make poster on their devices or system provided from the college",
grules:"General Rules:",
rule1:"Poster making Competition based on given topic.",
rule2:"Participant can make poster on their devices or system provided from the college",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",
fee1:"Rs. 150/- per team of 3",
fee2:"10 per person",
coordinator1:"Mr. Akshay Krishna",
coordinator1no:"6238940904",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306",
coordinator3:"Ms. Vinitha",
coordinator3no:"9497632571"},

//22
{title:"PIC-POW",
para:"●Spot Photography Event,Cash Prize of 500",
grules:"General Rules:",
rule1:"	One person must send only one photo",
rule2:"	Anyone submitting 2 or more photos from same participant will be disqualified.",
rule3:"	Editing other than manipulation is allowed.",
room:"",
fee1:"10/- Per head",
fee2:"",
coordinator1:"Mr. Shaheer P V",
coordinator1no:"9895730591",
coordinator2:"Ms. Akhila E",
coordinator2no:"9847788306"},


//24
{title:"SUIII",
para:"Jump high as Cristiano Ronaldo’s jump height,Gift worth 500",
grules:"General Rules:",
rule1:"Two chance per person",
rule2:"The decision of the authorities will be final and irrefutable.",
room:": Jawaharlal Gardens ",
fee2:"",
coordinator1:"Mr. Mohammed Niyaz",
coordinator1no:": 8848806940",
coordinator2:"Ms. Anu TP",
coordinator2no:"9846634066"},

//25
{title:"PENALTY-SHOOTOUT",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"One chance ",
rule2:"The decision of the authorities will be final and irrefutable",
room:"Ground",
fee2:"10/- Per head",
coordinator1:": Mr. Piyush Santhosh",
coordinator1no:"8086392043",
coordinator2:" Ms. Anu TPU ",
coordinator2no:"984663406"},

//26
{title:"QUIZZIE-BUZZIE",
para:"Quiz based Technical Topic,Gift worth 500",
grules:"General Rules:",
rule1:"• Each round will be 10 minutes each..",
room:"Room No. 218",
fee1:"Free",
coordinator1:"Mr. Mohammed Hussain",
coordinator1no:"7025707936",
coordinator2:"Ms. Anu TP",
coordinator2no:"9846634066"},

//27
{title:"ETHICAL-HACKING-AWARENESS",
para:"Awareness about Ethical Hacking",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
room:"506",fee1:"FREE",
coordinator1:"Ms. Gopika M",
coordinator1no:" 6235451723",
coordinator2:"Ms. Amritha Devadasan",
coordinator2no:"8075942401"}
]


//aero datas

//1
let aero=[{title:"PLANETARIUM",
para:"15 minutes of realistic space experience, chance to go beyond our planet and explore what lies unseen.",
grules:"General Rules:",
rule1:"30 persons can watch at the same time ",
rule2:"Registration is required with Rs.120 per head . ",
rule3:"The event is open for all . ",
rule4:"Student ID’s must be carried . ",   
room:"CLASS ROOM 1",
fee1:"Rs. 120/- per head ",
coordinator1:"Surabhi R  ",
coordinator1no:"8848870510 ",
coordinator2:"Kailash Karunakaran ",
coordinator2no:"9745143634"},



//2
{title:"FLIGHT-SIMULATOR",
para:"Flight simulator is a chance of experiencing a realistic cockpit for yourself with the virtual piloting of Cessna . A Flight Simulator with Joy Stick and an Online flight simulator will be brought.",
grules:"General Rules: ",
rule1:"Simulation is done currently for free.",
rule2:"Registration is required",
rule3:"The event is open for all . ",  
rule4:"Student ID’s must be carried ",
room:"BTech block Room No.208",
fee1:"",
coordinator1:"Anand D ",
coordinator1no:"7558020984 ",
coordinator2:"Kailash Karunakaran",
coordinator2no:"9745143634 "},


//3
{title:"GLIDER-MODELLING",
para:"Ever tried making a plane yourself? This workshop will help in making, fabricating and flying it own your own.",
grules:"General Rules: ",
rule1:"Registration is required with Rs.200 per team . ",
rule2:"  The team can have 2 members ",
rule3:"Student ID’s must be carried .",
rule4:" Registration is required ",   
room:"3rd floor Smart class room ",
fee1:"RS.100/PER HEAD.",
coordinator1:"Gopika Gopinath ",
coordinator1no:"8606342293",
coordinator2:"Mohamed Sameer T.K ",
coordinator2no:"8547279042"},


//4
{title:"CUBESATE",
para:"Have you ever wondered how a satellite works and what is the manufacturing procedures, then this seminar is dedicated for you. It's a live workshop of the Cubesate",
grules:"General Rules: ",
rule1:"This workshop has registration of  ₹200   per head	",
rule2:" Registration is required ",
rule3:"The event is open for all.",
rule4:"Student ID’s must be carried .",   
room:"3rd floor Seminar hall",
fee1:"Rs. 200/- per head",
coordinator1:"Abhishek P S ",
coordinator1no:"9207356485",
coordinator2:"Ajith V S ",
coordinator2no:"8667704870 "},


//5
{title:"ILLUSION-HALL",
para:"An exhibition of anamorphic illusion sculpture . An illusion is a distortion of the senses, which can reveal how the mind normally organizes and interprets sensory stimulation",
grules:"General Rules: ",
rule1:"This workshop has registration of  ₹    per head	",
rule2:"  Registration is required ",
rule3:"The event is open for all.",
rule4:" Student ID’s must be carried .",   
room:"BTech block Room No.406",
fee1:"",
coordinator1:"Sreelakshmi N ",
coordinator1no:"9946942380 ",
coordinator2:"Amal Raj ",
coordinator2no:"9447843204"},



//6
{title:"JET-ENGINE-PROTOTYPE",
para:"Your fascination of Jet Engine will be fed through this prototype where you can feel the afterburner of a jet engine & learn how it works .",
grules:"General Rules: ",
rule1:"",
rule2:"  ",
rule3:"",
rule4:" ",   
room:" Stall",
fee1:"",
coordinator1:"Jovin Joseph Saratho ",
coordinator1no:"9961548115",
coordinator2:"Rinchu P ",
coordinator2no:"8593081848"},




//7
{title:"BRAIN-CYCLE",
para:"Test the working of the brain simultaneously.",
grules:"General Rules: ",
rule1:"The participant have to ride the bicycle through a predefined path . But there is mystery hidden in bicycle",
rule2:"  ",
rule3:"",
rule4:" ",   
room:"B.Arch Road",
fee1:"",
coordinator1:"Soorya K S  ",
coordinator1no:"",
coordinator2:"John George v",
coordinator2no:" 9791287775"},



//8
{title:"BATTLE-ROYAL",
para:"A harmless live battleroyal game, which is a replica of the mobile game PUBG, where bullets are converted to laser.",
grules:"General Rules: ",
rule1:"The duration of the game is 15 minutes ",
rule2:"A team of 3 can participate ",
rule3:"A team of 3 can participate ",
rule4:"A laser toy gun is used as the weapon ",   
room:"Class room 4",
fee1:"Rs. 10/- per head ",
fee2:"Rs. 30/- per team",
coordinator1:"Abhijith C J ",
coordinator1no:"8921557365",
coordinator2:"Mohamed Sameer T K  ",
coordinator2no:"8547279042"},



//9
{title:"LASER-MAZE",
para:"A laser orientated maze with the task to travel a path without touching the laser and bring the item from the centre of the maze",
grules:"General Rules: ",
rule1:"The duration of the game is 10 minutes ",
rule2:"A maze is constructed using the rays of laser  ",
rule3:"A participant must follow the path by without touching the laser",
rule4:" ",   
room:"Class room.4",
fee1:"",
coordinator1:"Abdul Wasif Khan ",
coordinator1no:"6301169095",
coordinator2:"Mohamed Sameer T K ",
coordinator2no:"8547279042"},



//10
{title:"POSTER-PRESENTATION",
para:"Had an innovative idea and always tried to share it but never had a chance. This is your chance to come forward and present your innovative mind. D o your paper presentation on the recents trends in engineering .",
grules:"General Rules: ",
rule1:"",
rule2:"  ",
rule3:"",
rule4:" ",   
room:"Smart class  ",
fee1:"Rs. 100/- per head ",
coordinator1:"Noora A K ",
coordinator1no:"7736769244",
coordinator2:"Amal Raj ",
coordinator2no:"9447843204"},


//11
{title:"PHOTOGRAPHY-COMPETITION",
para:"A place to exhibit your skill in photography and be judged by your efficency and creativity.All the Photographs will be exhibited",
grules:"General Rules: ",
rule1:"Mobile phone can only be used  ",
rule2:"Should not be copied from any other platform . ",
rule3:"Manipulation not allowed .",
rule4:"Photos must be in JPEG or JPG format . ",   
room:"BTech block Room No.406",
fee1:"Rs. 20/- per head ",
coordinator1:"Swathi Krishna K ",
coordinator1no:"8086680049",
coordinator2:"Sujesh G ",
coordinator2no:"9745169994"}
]



//mech datas

//1
let mech=[{title:"Mecholution",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"Machinery-EXPO",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Mech-Corner",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Lathe-Master",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Design-Competition",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Tech-Talk",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Project-Expo",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Bullet-Kick-Start-for-Girls",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}

]


//ece datas

//1
let ece=[{title:"DARK-ROOM",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//3
{title:"CIRCUIT-DEBUGGING",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//4
{title:"DIGITAL-POSTER-DESIGNING-COMPETITION",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//5
{title:"ELECTRONIC-PUZZLE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//6
{title:"SOLDERING-COMPETITION",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//7
{title:"ARDUINO-CODING-COMPETITION",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


//8
{title:"QUIZ",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"CREATIVE-PHOTOGRAPHY",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"VIRTUAL-DRIVING",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"TRACK-RACING",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"STACK-ATTACK",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"LANDING-PAD",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"BOWLING-ALLEY",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"HIT-THE-POINT",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"NUTSTACKER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},


{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

{title:"Microstrip-Antenna-Design",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}
]


//civil datas

//1
let civil=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",
coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}
]


//law datas

//1
let law=[{title:"HOLOGRAM,AR&VR",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"FLURO-LEAGUE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}
]


//mba datas

//1
let mba=[{title:"WISDOM-MAN-CORPORATE-MANAGER",
para:"Virtual Reality (VR), Augmented Reality (AR), Experience Metaverse, Hologram Show, Racing console, Open world game, FIFA & other games",
grules:"General Rules:",
rule1:"Each round will be 10-15 minutes each.",
rule2:"The decision of the authorities will be final and irrefutable.",
rule3:"",
rule4:"",
room:"Room No. 210",fee1:"Rs. 50/- per head",
fee2:"",coordinator1:"Mr. Mohammed Nihal",
coordinator1no:"9526330896",
coordinator2:"Ms. Sreekala R",
coordinator2no:"8606314431"},


//2
{title:"BOOM-BANG",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"FOOTBALL-FEVER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"PARALLEL-WORLD-AR-VR",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"LETS-NACHO",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"MIND-TWISTER",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"},

//2
{title:"DRAGON-SHOE",
para:"Fluorescent football. Participants need to play in a dark room with fluorescent dress and ball. Gift worth 1000",
grules:"General Rules:",
rule1:"Each round will be 10 minutes each.",
rule2:"There will be 1 match at a time and the participants will be provided with dress and football.",
rule3:"The winner will be declared at the end of the event.",
rule4:"The decision of the authorities will be final and irrefutable.",
room:"Room No. 203",fee1:"Rs. 150/- per team of 3",
fee2:"",coordinator1:"Mr. Mohammed Harish",
coordinator1no:"7306606253",
coordinator2:"Dr. U Vijay Sankar",
coordinator2no:"9846634066"}
]









module.exports={mech,civil,cse,aero,ece,law,mba}
