
//law datas

//1
let law=[{title:"THE-SOUVENIR",
para:"Introduces the field of its kind on legal heritage and to introduce about the rights and duties as the part of the society,Spot events shall be conducted in between for the visitors Free entry for all.",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"Nehru Academy of Law Premises",fee1:"",
fee2:"",coordinator1:"NEHA MATHEW",
coordinator1no:" 6282525574",
coordinator2:"DONIYA ELSA THOMAS:",
coordinator2no:"9496439651"},

{title:"THE-QUIZ-SHOW",
para:": Quiz is being conducted to create legal awareness among the students also to have the spirit of legal knowledge among all rounds:There shall be three rounds in total,In Round- I, there shall be negative marks for each wrong answer,In each round two questions each carrying 10 marks shall be asked,Each passing question shall have 5 marks. (Maximum 1 minute),Round II There shall be no negative marking,Round III will be buzzer round,",
grules:"General Rules:",
rule1:"The quiz will cover topics related to: Constitution General Knowledge Basic History and Science",
rule2:"Each Team shall consist of two participants",
rule3:"Mass answering is not entertained,Registration amount shall not be refunded,Participants are restricted from carrying any type of electronic gadgets, books or other reference material along with them,Judges decision shall be final",
rule4:"Coordinators shall have the right to amend the rules of the event",
room:"Shastra Hall- JCET Campus",
fee1:"100 per team",
fee2:"",
coordinator1:"THEERTHA REGHUNATH",
coordinator1no:"8848778280",
coordinator2:"MEERA T",
coordinator2no:": 9645420111"},


{title:"BRAVE-HEART",
para:"Extempore is a speech competition in which the topic shall be given on the spot They shall be given specified time for preparation and the speech shall be delivered. They will be allowed to participate only in their respective registered languages (English/Malayalam).",
grules:"General Rules:",
rule1:"Participants are free to participate individually, The registration fee shall be Rs.100 per participant Rounds: There shall be only one round.",
rule2:"If necessary a knock-out round will be conducted, The participant shall be allowed to participate only in the registered language (English/Malayalam), The topic will be given at the event venue.No participant will be allowed to choose the topic again",
rule3:"Time will be strictly followed, no extra time will be given Each participant shall be given four minutes to speak on a topic and the maximum time limit to think on the topic shall be limited to two minutes. A bell will ring at the end of three minutes to indicate that one minute is left to finish his/her speech, Another bell will ring at the end of four minutes",
rule4:"No alteration of participant will be allowed on the final day All the participant must report the concerned committee members 30 minutes before the scheduled time of the competition. The decision of the panel of judges and organizing committee regarding evaluation is final and binding, Registration amount shall not be refunded",
room:"Nehru Academy of Law Premises",
fee1:"200 per participants",
fee2:"",coordinator1:"NAFEESA THASNI K",
coordinator1no:"9746152483",
coordinator2:"DIVYA S",
coordinator2no:"8594051624"},


{title:"KNIVES-OUT",
para:"A team shall consist of 4 members. The event aims at learning about the circumstances surrounding a crime scene during the collection of physical evidence and analysis of the same. It is multidisciplinary and involves a systematic search of the crime scene with observation and documentation of the scene.",
grules:"General Rules:",
rule1:"All the participants are required to carry their own writing and drawing tools and examboard (one for a team). Each team comprising four participants shall be given maximum of 8 minutes to investigate the crime scene and jot-down relevant points.Teams can make rough sketches or graphs for their convenience during this time, Participants can analyze the crime scene and physical evidence by observing. Each team shall be required to record the observation in a given sheet and submit the investigation report. The Organizing Committee will provide Reporting Sheets. Each team shall be required to hypothesize the best possible story behind the incident and conclude the guilt of the suspect/s.",
rule2:"Participants shall be directed to the crime scene once they get acquainted with the plot",
rule3:"",
rule4:"",
room:"Nehru Academy of Law ",fee1:". 600 per team",
fee2:"",coordinator1:"ADARSH G K",
coordinator1no:"7034732170",
coordinator2:"MAYA MAYURA",
coordinator2no:"8921361452"},

{title:"HAMILTON",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ROGUE-TRADER",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"UNCHARTED",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"THE-MAD-MEN",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"MARGIN-CALL",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"THE-CREATIVE-BRAIN",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PHOTOGRAPHY-CONTEST",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"STAND-UP-COMEDY",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"SPOON-AND-CUP-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"INTELLECTUAL-GAME",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"LAVA-WALK",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PENALTY-SHOOTOUT",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PS4-GAME",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"SUMO-WRESTLING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-SHOOTING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ARROW-THROW",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"RING-THROW",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"PUSH-UP-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"HANGING-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"ARM-WRESTLING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"CUP-AND-PLATE-TOWER-CHALLENGE",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-CATERPILLAR",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},

{title:"BALLOON-POPPING",
para:"",
grules:"General Rules:",
rule1:"",
rule2:"",
rule3:"",
rule4:"",
room:"",
fee1:"",
fee2:"",
coordinator1:"",
coordinator1no:"",
coordinator2:"",
coordinator2no:""},
]
